use openssl to generate b2sums

diff --git a/abuild.in b/abuild.in
--- a/abuild.in
+++ b/abuild.in
@@ -1464,7 +1464,7 @@ create_apks() {
 
 		msg "Create checksum..."
 		# append the hash for data.tar.gz
-		local b2=$(b2sum "$dir"/data.tar.gz | cut -f1 -d' ')
+		local b2=$(openssl dgst -blake2b512 "$dir"/data.tar.gz | cut -f1 -d' ')
 		echo "b2sum = $b2" >> "$dir"/.PKGINFO
 
 		# control.tar.gz
@@ -2075,8 +2075,8 @@ checksum() {
 	done
 
 	msg "Updating the b2sums in APKBUILD..."
-	b2sums="$(cd "$srcdir" && b2sum $files)" \
-		|| die "b2sum failed"
+	b2sums="$(cd "$srcdir" && openssl dgst -blake2b512 $files)" \
+		|| die "b2sums failed"
 	echo "b2sums=\"$b2sums\"" >>"$APKBUILD"
 }
 
