amove

diff --git a/abuild.in b/abuild.in
--- a/abuild.in
+++ b/abuild.in
@@ -69,6 +69,26 @@ if [ "$(id -u)" -gt 0 ]; then
 	exit 1
 fi
 
+amove() {
+	[ -n "$subpkgdir" ] || return 1
+	# store directory
+	d="$(pwd -L)"
+	cd "$pkgdir"
+	local pattern f
+	for pattern; do
+		for f in ${pattern#/}; do # let shell expand the pattern
+		# only create dir if needed
+			if [ "${f%/*}" != "$f" ]; then
+				mkdir -p "$subpkgdir/${f%/*}"
+		fi
+			mv -v "$pkgdir"/$f "$subpkgdir/${f%/*}"
+			# cleanup
+			rmdir -p "$f" || rmdir -p "${f%/*}" || true
+		done
+	done
+	cd "$d"
+}
+
 want_check() {
 	[ "$skipcheck" ] && return 1
 	options_has "!check" && return 1
