fix

diff --git a/abuild.in b/abuild.in
--- a/abuild.in
+++ b/abuild.in
@@ -1113,6 +1113,8 @@ prepare_pkgconfig_provides() {
 		local f=${i##*/}
 		local v=$(PKG_CONFIG_PATH="$dir"/usr/lib/pkgconfig:"$dir"/usr/share/pkgconfig \
 			PKG_CONFIG_MAXIMUM_TRAVERSE_DEPTH=1 pkg-config \
+			--modversion ${f%.pc} | sed -E -e 's/-(alpha|beta|rc|pre)/_\1/')
+		$APK version --check --quiet $v || die "$i: pkgconf version $v is invalid"
 		echo "$pcprefix${f%.pc}=${v:-0}" >> "$controldir"/.provides-pc
 	done
 }
